version: 2
rules:
  - pattern: '!ENV\s+[A-Z_]+'
    reason: 'Ignore ENV variables in YAML'
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  - pattern: '!\*\*V\s+[A-Z_]+'
    reason: 'Ignore variables with tag !**V in YAML'
    paths:
      - '**/*.yaml'
      - '**/*.yml'

secret:
  ignored-paths:
    - 'iam-proxy-italia-project-demo-examples/spid_cie_oidc_django/provider/dumps/example.json'
    - 'iam-proxy-italia-project/conf/backends/cieoidc_backend.yaml'