{{- if not .Values.oidcop.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-proxy-italia.fullname" . }}-jwks
  labels:
    {{- include "iam-proxy-italia.labels" . | nindent 4 }}
type: Opaque
stringData:
  privateJwks: {{ .Values.oidcop.privateJwks | quote }}
  publicJwks: {{ .Values.oidcop.publicJwks | quote }}
{{- end }}
