{{- if and (empty .Values.satosa.keys.existingVolume) .Values.satosa.keys.privateKey .Values.satosa.keys.publicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-proxy-italia.fullname" . }}-keys
  labels:
    {{- include "iam-proxy-italia.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.satosa.keys.privateKeyFilename }}: {{ .Values.satosa.keys.privateKey | quote }}
  {{ .Values.satosa.keys.publicKeyFilename }}: {{ .Values.satosa.keys.publicKey | quote }}
{{- end }}
