{{- if and (not .Values.oidcop.jwks.existingVolume) (or .Values.oidcop.jwks.public.content .Values.oidcop.jwks.private.content) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-proxy-italia.fullname" . }}-oidcop-jwks
  labels:
    {{- include "iam-proxy-italia.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.oidcop.jwks.public.content }}
  public.json: {{ .Values.oidcop.jwks.public.content | quote }}
  {{- end }}
  {{- if .Values.oidcop.jwks.private.content }}
  private.json: {{ .Values.oidcop.jwks.private.content | quote }}
  {{- end }}
{{- end }}
