{{- if not .Values.secret.existingSecret }}
{{- $secretName := include "iam-proxy-italia.secret" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $encryptionKey := "" }}
{{- $salt := "" }}
{{- $stateKey := "" }}
{{- $hashSalt := "" }}
{{- $mongoPassword := "" }}
{{- $mongoBackendPassword := "" }}
{{- $mongoFrontendPassword := "" }}
{{- if $existingSecret }}
  {{- $encryptionKey = index $existingSecret.data "satosa-encryption-key" | b64dec }}
  {{- $salt = index $existingSecret.data "satosa-salt" | b64dec }}
  {{- $stateKey = index $existingSecret.data "satosa-state-encryption-key" | b64dec }}
  {{- $hashSalt = index $existingSecret.data "satosa-user-id-hash-salt" | b64dec }}
  {{- $mongoPassword = index $existingSecret.data "mongodb-password" | b64dec }}
  {{- $mongoBackendPassword = index $existingSecret.data "mongodb-backend-password" | b64dec }}
  {{- $mongoFrontendPassword = index $existingSecret.data "mongodb-frontend-password" | b64dec }}
{{- else }}
  {{- if .Values.satosa.encryption.key }}
    {{- $encryptionKey = .Values.satosa.encryption.key }}
  {{- else }}
    {{- $encryptionKey = randAlphaNum 32 }}
  {{- end }}
  {{- if .Values.satosa.encryption.salt }}
    {{- $salt = .Values.satosa.encryption.salt }}
  {{- else }}
    {{- $salt = randAlphaNum 32 }}
  {{- end }}
  {{- if .Values.satosa.encryption.stateKey }}
    {{- $stateKey = .Values.satosa.encryption.stateKey }}
  {{- else }}
    {{- $stateKey = randAlphaNum 32 }}
  {{- end }}
  {{- if .Values.satosa.encryption.userIdHashSalt }}
    {{- $hashSalt = .Values.satosa.encryption.userIdHashSalt }}
  {{- else }}
    {{- $hashSalt = randAlphaNum 32 }}
  {{- end }}
  {{- if .Values.mongodb.password }}
    {{- $mongoPassword = .Values.mongodb.password }}
  {{- else }}
    {{- $mongoPassword = randAlphaNum 32 }}
  {{- end }}
  {{- if .Values.mongodbBackend.password }}
    {{- $mongoBackendPassword = .Values.mongodbBackend.password }}
  {{- else }}
    {{- $mongoBackendPassword = randAlphaNum 24 }}
  {{- end }}
  {{- if .Values.mongodbFrontend.password }}
    {{- $mongoFrontendPassword = .Values.mongodbFrontend.password }}
  {{- else }}
    {{- $mongoFrontendPassword = randAlphaNum 32 }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "iam-proxy-italia.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  satosa-encryption-key: {{ $encryptionKey | quote }}
  satosa-salt: {{ $salt | quote }}
  satosa-state-encryption-key: {{ $stateKey | quote }}
  satosa-user-id-hash-salt: {{ $hashSalt | quote }}
  mongodb-password: {{ $mongoPassword | quote }}
  mongodb-backend-password: {{ $mongoBackendPassword | quote }}
  mongodb-frontend-password: {{ $mongoFrontendPassword | quote }}
{{- end }}
