{{- if and .Values.frontendsConfig (not .Values.configVolume.existingConfigMap) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-proxy-italia.fullname" . }}-frontends-config
  labels:
    {{- include "iam-proxy-italia.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.frontendsConfig }}
  {{ $key }}_frontend.yaml: |
{{ $val | indent 4 }}
  {{- end }}
{{- end }}
