{{- if not .Values.secret.existingSecret }}
{{- $secretName := include "iam-proxy-italia.secret" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $encryptionKey := "" }}
{{- $salt := "" }}
{{- $stateEncryptionKey := "" }}
{{- $userIdHashSalt := "" }}
{{- $mongoFrontendPassword := index .Values.mongodb.auth.passwords 0 }}
{{- $mongoBackendPassword := index .Values.mongodb.auth.passwords 1 }}

{{- if $existingSecret }}
  {{- $encryptionKey = index $existingSecret.data "satosa-encryption-key" | b64dec }}
  {{- $salt = index $existingSecret.data "satosa-salt" | b64dec }}
  {{- $stateEncryptionKey = index $existingSecret.data "satosa-state-encryption-key" | b64dec }}
  {{- $userIdHashSalt = index $existingSecret.data "satosa-user-id-hash-salt" | b64dec }}
{{- else }}
  {{- $encryptionKey = .Values.satosa.encryptionKey | default (randAlphaNum 32) }}
  {{- $salt = .Values.satosa.salt | default (randAlphaNum 32) }}
  {{- $stateEncryptionKey = .Values.satosa.stateEncryptionKey | default (randAlphaNum 32) }}
  {{- $userIdHashSalt = .Values.satosa.userIdHashSalt | default (randAlphaNum 32) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "iam-proxy-italia.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  satosa-encryption-key: {{ $encryptionKey | quote }}
  satosa-salt: {{ $salt | quote }}
  satosa-state-encryption-key: {{ $stateEncryptionKey | quote }}
  satosa-user-id-hash-salt: {{ $userIdHashSalt | quote }}
  mongodb-backend-password: {{ $mongoBackendPassword | quote }}
  mongodb-frontend-password: {{ $mongoFrontendPassword | quote }}
{{- end }}
