{{- if and .Values.microservicesConfig (not .Values.configVolume.existingConfigMap) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-proxy-italia.fullname" . }}-microservices-config
  labels:
    {{- include "iam-proxy-italia.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.microservicesConfig }}
  {{ $key }}.yaml: |
{{ $val | toYaml | indent 4 }}
  {{- end }}
{{- end }}
