# Check markdown documentation for broken links
# See https://github.com/lycheeverse/lychee-action

name: Docs link check

on:
  push:
    branches: [ master, dev ]
    paths: [ '**.md', 'docs/**' ]
  pull_request:
    branches: [ master, dev ]
    paths: [ '**.md', 'docs/**' ]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          skip_after_successful_duplicate: 'true'
          same_content_newer: 'true'

  linkcheck:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-${{ hashFiles('README.md', 'CONTRIBUTORS.md', 'CONTRIBUTING.md', 'docs/*.md') }}
          restore-keys: lychee-

      - name: Lychee link checker
        uses: lycheeverse/lychee-action@v2.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --no-progress --exclude 'localhost' --exclude 'iam-proxy-italia.example.org' --cache --max-cache-age 1d --max-concurrency 1 --max-retries 2 --accept 200,429 README.md CONTRIBUTORS.md CONTRIBUTING.md docs/*.md
          fail: true
